version: '{branch}-{build}'
image: Visual Studio 2017

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files\Java\jdk9
  - JAVA_HOME: C:\Program Files\Java\jdk10
  - JAVA_HOME: C:\Program Files\Java\jdk11
  - JAVA_HOME: C:\Program Files\Java\jdk12
  - JAVA_HOME: C:\Program Files\Java\jdk13

install:
  - ps: choco install ant --ignore-dependencies --version 1.10.12 -y
  - ps: $env:Path="$($env:JAVA_HOME)\bin;$($env:Path);C:\ProgramData\chocolatey\lib\ant"
  - ps: $env:ANT_OPTS="-Dfile.encoding=UTF-8"
  - java -version
  - ant -version

init:
  - git config --global core.autocrlf input

build_script:
  - ant jar

test: false

cache:
  - C:\Users\appveyor\.ant
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib

artifacts:
  - path: jkcemu.jar
