version: '{branch}-{build}'

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    JAVA_HOME: C:\Program Files\Java\jdk9
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    JAVA_HOME: C:\Program Files\Java\jdk10
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    JAVA_HOME: C:\Program Files\Java\jdk11
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    JAVA_HOME: C:\Program Files\Java\jdk12
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    JAVA_HOME: C:\Program Files\Java\jdk13
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    JAVA_HOME: C:\Program Files\Java\jdk14
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    JAVA_HOME: C:\Program Files\Java\jdk15
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    JAVA_HOME: C:\Program Files\Java\jdk16
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    JAVA_HOME: C:\Program Files\Java\jdk17

install:
  - ps: choco install ant --ignore-dependencies --version 1.10.12 -y
  - ps: $env:Path="$($env:JAVA_HOME)\bin;$($env:Path);C:\ProgramData\chocolatey\lib\ant"
  - ps: $env:ANT_OPTS="-Dfile.encoding=UTF-8"
  - java -version
  - ant -version

init:
  - git config --global core.autocrlf input

build_script:
  - ant jar

test: false

cache:
  - C:\Users\appveyor\.ant
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib

artifacts:
  - path: jkcemu.jar
