version: '{build}'
os: Windows Server 2012

environment:
  ANT_HOME: C:\ant\apache-ant-1.9.14
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.7.0

install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\ant\apache-ant-1.9.14" )) {
        (new-object System.Net.WebClient).DownloadFile(
        'https://www-eu.apache.org/dist//ant/binaries/apache-ant-1.9.14-bin.zip',
          'C:\ant-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\ant-bin.zip", "C:\ant")
      }
  - cmd: SET PATH=C:\ant\apache-ant-1.9.14\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: set ANT_OPTS=-Dfile.encoding=UTF-8
  - cmd: java -version
  - cmd: ant -version

init:
  - git config --global core.autocrlf input

build_script:
  - ant jar

test: false

cache:
  - C:\ant

artifacts:
  - path: jkcemu.jar
