@ECHO OFF

cd ..\src
jar cvmf Manifest.txt ..\jkcemu.jar ^
  lib\jkcemu_*.dll ^
  jkcemu\*.class ^
  jkcemu\audio\*.class ^
  jkcemu\base\*.class ^
  jkcemu\base\deviceio\*.class ^
  jkcemu\base\jversion\*.class ^
  jkcemu\disk\*.class ^
  jkcemu\emusys\*.class ^
  jkcemu\emusys\a5105\*.class ^
  jkcemu\emusys\ac1_llc2\*.class ^
  jkcemu\emusys\bcs3\*.class ^
  jkcemu\emusys\customsys\*.class ^
  jkcemu\emusys\etc\*.class ^
  jkcemu\emusys\huebler\*.class ^
  jkcemu\emusys\kccompact\*.class ^
  jkcemu\emusys\kc85\*.class ^
  jkcemu\emusys\lc80\*.class ^
  jkcemu\emusys\llc1\*.class ^
  jkcemu\emusys\poly880\*.class ^
  jkcemu\emusys\z1013\*.class ^
  jkcemu\emusys\z9001\*.class ^
  jkcemu\emusys\zxspectrum\*.class ^
  jkcemu\etc\*.class ^
  jkcemu\file\*.class ^
  jkcemu\image\*.class ^
  jkcemu\joystick\*.class ^
  jkcemu\net\*.class ^
  jkcemu\print\*.class ^
  jkcemu\programming\*.class ^
  jkcemu\programming\assembler\*.class ^
  jkcemu\programming\basic\*.class ^
  jkcemu\programming\basic\target\*.class ^
  jkcemu\settings\*.class ^
  jkcemu\text\*.class ^
  jkcemu\tools\*.class ^
  jkcemu\tools\calculator\*.class ^
  jkcemu\tools\debugger\*.class ^
  jkcemu\tools\filebrowser\*.class ^
  jkcemu\tools\fileconverter\*.class ^
  jkcemu\tools\findfiles\*.class ^
  jkcemu\tools\hexdiff\*.class ^
  jkcemu\tools\hexedit\*.class ^
  jkcemu\usb\*.class ^
  z80emu\*.class ^
  rom\a5105\*.bin ^
  rom\ac1\*.bin ^
  rom\bcs3\*.bin ^
  rom\c80\*.bin ^
  rom\customsys\*.bin ^
  rom\etc\*.bin ^
  rom\huebler\*.bin ^
  rom\kc85\*.bin ^
  rom\kccompact\*.bin ^
  rom\kramermc\*.bin ^
  rom\lc80\*.bin ^
  rom\llc1\*.bin ^
  rom\llc2\*.bin ^
  rom\nanos\*.bin ^
  rom\pcm\*.bin ^
  rom\poly880\*.bin ^
  rom\sc2\*.bin ^
  rom\slc1\*.bin ^
  rom\vcs80\*.bin ^
  rom\z1013\*.bin ^
  rom\z9001\*.bin ^
  rom\z9001\*.gz ^
  rom\zxspectrum\*.bin ^
  images\chess\*.png ^
  images\debug\*.png ^
  images\emusys\kc85\*.png ^
  images\etc\*.png ^
  images\icon\*.png ^
  images\keyboard\*.png ^
  images\keyboard\a5105\*.png ^
  images\keyboard\kc85\*.png ^
  images\keyboard\lc80\*.png ^
  images\keyboard\poly880\*.png ^
  images\keyboard\sc2\*.png ^
  images\keyboard\z1013\*.png ^
  images\keyboard\z9001\*.png ^
  images\keyboard\zxspectrum\128k\*.png ^
  images\keyboard\zxspectrum\48k\*.png ^
  images\psg\*.png ^
  images\s\audio\*.png ^
  images\s\debug\*.png ^
  images\s\disk\*.png ^
  images\s\edit\*.png ^
  images\s\etc\*.png ^
  images\s\file\*.png ^
  images\s\nav\*.png ^
  images\x\audio\*.png ^
  images\x\debug\*.png ^
  images\x\disk\*.png ^
  images\x\edit\*.png ^
  images\x\etc\*.png ^
  images\x\file\*.png ^
  images\x\nav\*.png ^
  disks\harddisks.csv ^
  disks\a5105\*.gz ^
  disks\kc85\*.gz ^
  disks\kccompact\*.gz ^
  disks\nanos\*.gz ^
  disks\pcm\*.gz ^
  disks\z1013\*.gz ^
  disks\z9001\*.gz ^
  help\*.htm ^
  help\bcs3\*.htm ^
  help\disk\*.htm ^
  help\kramermc\*.htm ^
  help\tips\*.htm ^
  help\tools\*.htm ^
  help\tools\basicc\*.htm ^
  help\z1013\*.htm
cd ..\cmd
